# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yevhenorlov.com
email: yevhenorlov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  блог про веб-розробку, цифрове мистецтво і красивий код
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yevhenorlov.com" # the base hostname & protocol for your site
twitter_username: yevhenorlov
github_username:  yevhenorlov

# Build settings
markdown: kramdown
# highlighter: pygments

sass:
  sass_dir: assets/sass/precompiled

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
