# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yevhen orlov
email: studio@yevhenorlov.com
description: > # this means to ignore newlines until "baseurl:"
  computer music, front-end, creative coding
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# twitter_username: yevhenorlov
# github_username:  yevhenorlov

# Build settings
markdown: kramdown
